### Funciones de activación

In [4]:
import tensorflow as tf
import tensorflow.nn as nn
session = tf.Session()

#### Función relu
- Elimina valores negativos.

In [3]:
#----- Función relu -----
print(session.run(nn.relu([-5., 5., 15.])))

[ 0.  5. 15.]


In [4]:
#----- Función relu6 -----
print(session.run(nn.relu6([-5., 5., 15.])))

[0. 5. 6.]


#### Función sigmoide o logística
- Continua y derivable.

In [5]:
print(session.run(nn.sigmoid([-1., 0., 1., 2.])))

[0.26894143 0.5        0.7310586  0.880797  ]


#### Función tangente hiperbólica
- Continua y derivable.
- Rango de valores entre -1 y 1.

In [7]:
print(session.run(nn.tanh([-2., -1., 2., 1., 2.])))

[-0.9640276 -0.7615942  0.9640276  0.7615942  0.9640276]


#### Función softsign
- Versión continua de la función sign.
- No es derivable.

In [8]:
print(session.run(nn.softsign([-2., -1., 2., 1., 2.])))

[-0.6666667 -0.5        0.6666667  0.5        0.6666667]


#### Función softplus
- Versión continua y derivable de la función relu.

In [10]:
print(session.run(nn.softplus([-2., -1., 0., 1., 2.])))

[0.12692805 0.31326166 0.6931472  1.3132616  2.126928  ]


#### Función ELU (Exponencial Lineal Unitaria)

In [11]:
print(session.run(nn.elu([-2., -1., 0., 1., 2.])))

[-0.86466473 -0.63212055  0.          1.          2.        ]
