### Introducción a TensorFlow
1. Importación o generación del conjunto de datos.
2. Transformación y normalización de los datos.
3. División del conjunto de datos en conjuntos de entrenamiento, validación y test.
4. Definir los hiperparámetros del algoritmo.

In [9]:
import tensorflow as tf
%config IPCompleter.greedy = True

In [7]:
#----- HIPERPARÁMETROS -----
learning_rate = 0.01 #ratio de aprendizaje
batch_size = 50 #tamaño de la muestra
iteration = 10000 #número de iteraciones

5. Inicializar variables y placeholders

In [8]:
x = tf.constant(30)
#(tipo de dato, [cantidad de datos, vectores 3D])
x_input = tf.placeholder(tf.float32, [None, 3])
y_input = tf.placeholder(tf.float32, [None, 5])

6. Definir la estructura del modelo del algoritmo.
$$y = mx+n$$

In [ ]:
y_pred = tf.add(tf.multiply(m_matrix, x_input), n_vector)

7. Declarar la función de pérdidas (loss function)
$$MSE = \frac{\sum_{i=1}^n(y_{actual} - y_{pred})^2}{n}$$

In [ ]:
loss = tf.reduce_mean(tf.square(y_actual - y_pred))

8. Inicializar y entrenar el modelo anterior

In [ ]:
with tf.Session(graph = graph) as session:
    ...
    session.run(...)
    ...

In [ ]:
session = tf.Session(graph = graph)
...
session.run(...)
...

9. Evaluación del modelo.
10. Ajustar los hiper-parámetros.
11. Publicar (subir a producción) y predecir nuevos resultados.

### Definición de tensores
Un tensor es un vector o matriz (estructura n-dimensional)

In [14]:
#----- Tensor de ceros -----
zero_t = tf.zeros([3, 4, 6])
zero_t

<tf.Tensor 'zeros_4:0' shape=(3, 4, 6) dtype=float32>

In [15]:
#----- Tensor de unos -----
ones_t = tf.ones([3, 4])
ones_t

<tf.Tensor 'ones:0' shape=(3, 4) dtype=float32>

In [17]:
#----- Tensor relleno de 7s -----
filled_t = tf.fill([4, 5, 2], 7)
filled_t

<tf.Tensor 'Fill:0' shape=(4, 5, 2) dtype=int32>

In [18]:
#----- Tensor a partir de una constante -----
cte_t = tf.constant([1, 2, 3, 4, 5]) #Vector de 5 filas
cte_t

<tf.Tensor 'Const_2:0' shape=(5,) dtype=int32>

#### Tensores por tamaño

In [19]:
#----- Tensor de tamaño de cte_t -----
zero_sim = tf.zeros_like(cte_t)
zero_sim

<tf.Tensor 'zeros_like:0' shape=(5,) dtype=int32>

In [20]:
ones_sim = tf.ones_like(cte_t)
ones_sim

<tf.Tensor 'ones_like:0' shape=(5,) dtype=int32>

#### Tensor en forma de secuencia
- linspace()
- range()

In [24]:
sec_t = tf.linspace(start = 0.0, stop = 1.0, num = 5)
sec_t

<tf.Tensor 'LinSpace_3:0' shape=(5,) dtype=float32>

In [26]:
range_seq = tf.range(start = 5.0, limit = 15.0, delta = 4.0)
range_seq # -> [5, 9, 13]

<tf.Tensor 'range_1:0' shape=(3,) dtype=float32>

#### Tensores aleatorios

In [30]:
#----- Tensor aleatorio de 3x4 con valores entre 0 y 1 -----
rand_unif_t = tf.random_uniform([3, 4], minval = 0, maxval = 1)
rand_unif_t

<tf.Tensor 'random_uniform:0' shape=(3, 4) dtype=float32>

In [31]:
#----- Tensor aleatorio con distribución normal -----
rand_norm_t = tf.random_normal([3, 4], mean = 0.0, stddev = 1.0)
rand_norm_t

<tf.Tensor 'random_normal:0' shape=(3, 4) dtype=float32>

In [32]:
#----- Tensor aleatorio con distribución normal truncada -----
rand_trunc_normal_t = tf.truncated_normal([3, 4], mean = 0.0, stddev = 1.0)
rand_trunc_normal_t

<tf.Tensor 'truncated_normal:0' shape=(3, 4) dtype=float32>

In [34]:
tf.random_shuffle(rand_unif_t) #Barajeo de los datos

<tf.Tensor 'RandomShuffle_1:0' shape=(3, 4) dtype=float32>

In [36]:
tf.random_crop(rand_norm_t, [2, 6]) #Reorganización de datos

<tf.Tensor 'random_crop:0' shape=(2, 6) dtype=float32>

### Introducción a las variables

In [38]:
#----- Pasamos de tensor a variable -----
tf.Variable(rand_norm_t)

<tf.Variable 'Variable_1:0' shape=(3, 4) dtype=float32_ref>

In [39]:
#----- Pasamos de constante a tensor -----
tf.convert_to_tensor(5)

<tf.Tensor 'Const_3:0' shape=() dtype=int32>

In [40]:
#----- Pasamos de array a tensor -----
tf.convert_to_tensor([1, 2, 3, 4, 5])

<tf.Tensor 'Const_4:0' shape=(5,) dtype=int32>

### Placeholder vs variables

#### Variables.
- Parámetros del modelo, TF los utiliza para optimizar el resultado de nuestro algoritmo.

In [42]:
#----- Inicialización de variables -----
my_var = tf.Variable(tf.zeros([3, 4]))
session = tf.Session()
inits = tf.global_variables_initializer()
session.run(inits)

#### Placeholders.
- Objeto que permite recibir información de datos de un tipo y tamaño concreto.

In [5]:
import numpy as np
#----- Distribución aleatoria en una matriz 2x2 -----
x_vals = np.random.rand(2, 2)
x_vals

array([[0.17850636, 0.53373732],
       [0.69998723, 0.30688572]])

In [7]:
session = tf.Session()
x = tf.placeholder(tf.float32, shape = [2, 2])
y = tf.identity(x)
session.run(y, feed_dict = {x: x_vals})

array([[0.17850636, 0.5337373 ],
       [0.69998723, 0.30688572]], dtype=float32)

In [48]:
x

<tf.Tensor 'Placeholder_6:0' shape=(2, 2) dtype=float32>

In [49]:
y

<tf.Tensor 'Identity:0' shape=(2, 2) dtype=float32>

### Varias inicializaciones dependientes

In [50]:
session = tf.Session()
first_var = tf.Variable(tf.zeros([3, 4]))
session.run(first_var.initializer)

second_var = tf.Variable(tf.zeros_like(first_var))
session.run(second_var.initializer)

In [51]:
second_var

<tf.Variable 'Variable_5:0' shape=(3, 4) dtype=float32_ref>

### Matrices en TensorFlow

In [8]:
import tensorflow as tf
session = tf.Session()
%config IPCompleter.greedy = True

1. Creación de matrices

In [19]:
identity = tf.diag([1., 1., 1., 1.])
identity

<tf.Tensor 'Diag_1:0' shape=(4, 4) dtype=float32>

In [20]:
print(session.run(identity))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [21]:
A = tf.truncated_normal([3, 4])
print(session.run(A))

[[-1.6452596   0.800701   -0.12903592  1.4855534 ]
 [-1.039341   -1.6885188   0.85675603 -0.2225354 ]
 [-0.7676597   0.20998837 -1.4787811   1.6418428 ]]


In [22]:
B = tf.fill([3, 4], 1988.)
print(session.run(B))

[[1988. 1988. 1988. 1988.]
 [1988. 1988. 1988. 1988.]
 [1988. 1988. 1988. 1988.]]


In [23]:
C = tf.random_uniform([4, 3])
print(session.run(C))

[[0.85733604 0.6575885  0.8073814 ]
 [0.8846265  0.482458   0.5824653 ]
 [0.3289051  0.37465823 0.48644626]
 [0.848379   0.67889416 0.47660804]]


In [24]:
import numpy as np
data = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.]])
D = tf.convert_to_tensor(data)
print(session.run(D))

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


#### Operación con matrices

In [25]:
print(session.run(A+B))

[[1988.1954 1986.571  1988.6531 1988.7528]
 [1987.9207 1988.1842 1988.9701 1987.8618]
 [1987.1545 1988.5078 1989.2051 1987.2487]]


In [26]:
print(session.run(A-A))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [27]:
print(session.run(tf.matmul(A, C)))

[[-1.5117857  -1.0521741  -0.40214577]
 [-0.12470692 -0.13615209 -0.17703986]
 [-0.554613   -0.78642315 -0.24331848]]


In [28]:
print(session.run(tf.matmul(A, identity)))

[[ 0.5738312   1.3446224  -0.4731415   0.72016805]
 [ 0.68621933 -0.63117903 -1.2573658  -0.9140176 ]
 [ 0.31749785 -1.6556435   0.32247967  0.32617998]]


#### Transpuesta y determinante de matrices

In [29]:
print(session.run(tf.transpose(D)))

[[1. 4. 7.]
 [2. 5. 8.]
 [3. 6. 9.]]


In [30]:
print(session.run(tf.transpose(A)))

[[-0.6057502  -0.7586407   0.42716825]
 [-0.01458424  1.4621426   1.7662864 ]
 [ 0.613675    1.0226214  -0.6547976 ]
 [ 0.39200243  0.23724805 -0.10168858]]


In [31]:
print(session.run(tf.matrix_determinant(D)))

6.66133814775094e-16


In [35]:
E = tf.convert_to_tensor(np.array([[1., 2., 3.], [-3., -6., -1.], [0., 5., -3.]]))
print(session.run(tf.matrix_determinant(E)))

-40.0


In [36]:
print(session.run(tf.matrix_inverse(E)))

[[-0.575 -0.525 -0.4  ]
 [ 0.225  0.075  0.2  ]
 [ 0.375  0.125  0.   ]]


#### Descomposición de matrices

In [38]:
print(session.run(tf.cholesky(identity)))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


#### Valores y vectores propios

In [39]:
#----- Vectores propios -----
print(session.run(tf.self_adjoint_eig(E)))

(array([-10.24888536,  -0.66882335,   2.91770871]), array([[ 0.21442787,  0.60489799, -0.76688924],
       [ 0.80402486,  0.3364893 ,  0.49022339],
       [-0.55458517,  0.72171557,  0.41420034]]))


In [40]:
#----- Valores propios -----
print(session.run(tf.self_adjoint_eigvals(E)))

[-10.24888536  -0.66882335   2.91770871]


In [41]:
#----- Valores propios y vectores propios -----
print(session.run(tf.self_adjoint_eig(E)))

(array([-10.24888536,  -0.66882335,   2.91770871]), array([[ 0.21442787,  0.60489799, -0.76688924],
       [ 0.80402486,  0.3364893 ,  0.49022339],
       [-0.55458517,  0.72171557,  0.41420034]]))


### Operaciones aritméticas con TensorFlow

In [10]:
import tensorflow as tf
session = tf.Session()

In [11]:
x = 3
y = 4

In [12]:
print(session.run(tf.add(x, y)))

7


In [13]:
print(session.run(tf.subtract(x, y)))

-1


In [14]:
print(session.run(tf.multiply(x, y)))

12


In [18]:
print(session.run(tf.div(x, y)))

0


In [50]:
print(session.run(tf.floordiv(7.0, 3.0)))

2.0


In [51]:
print(session.run(tf.mod(23., 5.)))

3.0


In [53]:
#----- Producto cruz para vectores 3-dim -----
print(session.run(tf.cross([1., 0., 0.], [0., 1., 0.])))

[0. 0. 1.]


### Funciones matemáticas

In [57]:
x = [-3., -2., -1., 0., 1., 2.]
print(session.run(tf.abs(x)))

[3. 2. 1. 0. 1. 2.]


In [59]:
print(session.run(tf.ceil(6.4)))

7.0


In [60]:
print(session.run(tf.floor(6.4)))

6.0


In [61]:
print(session.run(tf.round(6.4)))

6.0


In [62]:
print(session.run(tf.sin(x)))

[-0.14112    -0.90929747 -0.84147096  0.          0.84147096  0.9092974 ]


In [63]:
print(session.run(tf.cos(x)))

[-0.9899925  -0.4161468   0.5403023   1.          0.5403023  -0.41614684]


In [64]:
print(session.run(tf.tan(x)))

[ 0.14254653  2.18504    -1.5574079   0.          1.5574077  -2.1850398 ]


In [65]:
print(session.run(tf.log(x)))

[      nan       nan       nan      -inf 0.        0.6931472]


In [66]:
y = [4., 3., 7., -4., -3., 7.]

In [67]:
print(session.run(tf.maximum(x, y)))

[4. 3. 7. 0. 1. 7.]


In [68]:
print(session.run(tf.minimum(x, y)))

[-3. -2. -1. -4. -3.  2.]


In [70]:
print(session.run(tf.negative(y)))

[-4. -3. -7.  4.  3. -7.]


In [71]:
print(session.run(tf.pow(x, y)))

[ 81.  -8.  -1.  inf   1. 128.]


In [72]:
print(session.run(tf.sqrt(x)))

[      nan       nan       nan 0.        1.        1.4142135]


In [73]:
print(session.run(tf.rsqrt(x)))

[       nan        nan        nan        inf 1.         0.70710677]


In [74]:
print(session.run(tf.square(x)))

[9. 4. 1. 0. 1. 4.]


In [75]:
print(session.run(tf.sign(x)))

[-1. -1. -1.  0.  1.  1.]


### Otras funciones

In [76]:
#----- Derivada gamma de euler -----
print(session.run(tf.digamma(x)))

[       inf        inf        inf        inf -0.5772159  0.4227842]


In [77]:
#----- Logaritmo natural de la función beta -----
print(session.run(tf.lbeta(x)))

nan


In [78]:
#----- Logaritmo natural de la función gamma -----
print(session.run(tf.lgamma(x)))

[inf inf inf inf  0.  0.]


In [79]:
#----- Error normalizado de la gausiana -----
print(session.run(tf.erf(x)))

[-0.9999779  -0.9953223  -0.84270084  0.          0.84270084  0.9953223 ]


In [80]:
#----- Complementaria de la función anterior -----
print(session.run(tf.erfc(x)))

[1.9999778  1.9953222  1.8427008  1.         0.1572992  0.00467773]


In [81]:
#----- Suma cuadrado de las diferencias -----
print(session.run(tf.squared_difference(x, y)))

[49. 25. 64. 16. 16. 25.]


### Funciones propias

In [84]:
def custom_parabola(value):
    #----- y = 5x2 - 7x + 15 -----
    return tf.subtract(5*tf.square(value), 7*value) + 15

In [85]:
print(session.run(custom_parabola(5)))

105
